### ISSUE TITLE
Download schlägt immer fehl.

### ISSUE THREAD

**Issue by Serph91P** [ChaoticByte/GronkhTV-Downloader#4]
bekomme immer nach ein paar % an download diesen Fehler:
```
File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```
Danach kommt dieser nur noch.

**Comment by ChaoticByte** [comment]
Hey, entschuldige bitte die späte Antwort, Github hat mir keine Notifications mehr angezeigt.

**Comment by ChaoticByte** [comment]
Okay, ich habe noch ein paar Fragen:
* Tritt der Fehler noch immer auf, oder funktioniert das inzwischen?
* Wie schnell ist deine Internetleitung?
* Konntest du nach diesem Fehler weiterhin Videos auf Gronkh.TV schauen?
* Hast du vor diesem Fehler bereits Streams herunterladen können?
* Welches Betriebssystem verwendest du? Windows, Linux, Mac?

Es könnte sein, dass die GronkhTV-Server ein Ratelimiting verwenden, das bei vielen schnell aufeinanderfolgenden Anfragen (Download der Videofragmente) dicht macht und deiner IP-Adresse temporär keine Daten mehr sendet. Wenn du eine besonders schnelle Internetverbindung hast, könnte das der Fall sein.

**Comment by Serph91P** [comment]
> Okay, ich habe noch ein paar Fragen:
> 
> * Tritt der Fehler noch immer auf, oder funktioniert das inzwischen?
> * Wie schnell ist deine Internetleitung?
> * Konntest du nach diesem Fehler weiterhin Videos auf Gronkh.TV schauen?
> * Hast du vor diesem Fehler bereits Streams herunterladen können?
> * Welches Betriebssystem verwendest du? Windows, Linux, Mac?
> 
> Es könnte sein, dass die GronkhTV-Server ein Ratelimiting verwenden, das bei vielen schnell aufeinanderfolgenden Anfragen (Download der Videofragmente) dicht macht und deiner IP-Adresse temporär keine Daten mehr sendet. Wenn du eine besonders schnelle Internetverbindung hast, könnte das der Fall sein.
> 
> Ich kann mit meiner ~ 200 Mbit/s Leitung problemlos Streams herunterladen.

Ich glaub der letzte Satz ist der wichtigste Punkt. Aber zu deinen Fragen:

- Ja ging wieder aber auch nur bis ich in das vermutete rate Limit Reinlaufe. Hatte es auch schon mit yt-dl versucht, mit dem gleichen Ergebnis. Ich könnte früher die vods einfach runterladen.
- 1gig
- müsste ich testen ob ich weiter Videos schauen kann.
- jo könnte ich, ist aber schon eine Weile her.
- linux

**Comment by ChaoticByte** [comment]
Ja, das deutet alles auf Ratelimiting hin.

**Comment by ChaoticByte** [comment]
@Serph91P Kannst du bitte probieren, ob [bugfix/ratelimiting](https://raw.githubusercontent.com/ChaoticByte/GronkhTV-Downloader/bugfix/ratelimiting/gtv-dl.py) funktioniert?
Das Ratelimit muss vmtl. noch getweaked werden. Mit meiner Internetleitung kommen nur etwa 13 Megabyte pro Sekunde an. Eventuell sind auch 25 Mbyte/s schon zu viel.

**Comment by Serph91P** [comment]
> @Serph91P Kannst du bitte probieren, ob [bugfix/ratelimiting](https://raw.githubusercontent.com/ChaoticByte/GronkhTV-Downloader/bugfix/ratelimiting/gtv-dl.py) funktioniert? Das Ratelimit muss vmtl. noch getweaked werden. Mit meiner Internetleitung kommen nur etwa 13 Megabyte pro Sekunde an. Eventuell sind auch 25 Mbyte/s schon zu viel.

definitiv irgendein limit. Gleicher Fehler. Kann auf Gronkh.tv nichts mehr anschauen. Bin bis 6% gekommen.

**Comment by ChaoticByte** [comment]
> definitiv irgendein limit. Gleicher Fehler. Kann auf Gronkh.tv nichts mehr anschauen. Bin bis 6% gekommen.

Um das Problem zu lösen muss die Variable `RATELIMIT` (in bytes/s) in Zeile 74 getweaked werden. Ich habe ja leider keine Internetverbindung, die schnell genug ist um das Ratelimit der GTV CDN Server zu erreichen. Könntest du bitte von `13000000` (13 MByte/s) aus hochgehen und damit herausfinden ab wann das triggert?

Wenn du willst kannst du auch das Repo forken, bei dir vom Branch bugfix/ratelimiting aus einen eigenen Branch abzweigen (z.B. bugfix/ratelimiting-tweak), und im Anschluss einen PR von deinem Branch nach bugfix/ratelimiting in diesem Repo machen. So würdest du in der Liste der Contributor auftauchen.

**Comment by Serph91P** [comment]
> > definitiv irgendein limit. Gleicher Fehler. Kann auf Gronkh.tv nichts mehr anschauen. Bin bis 6% gekommen.
> 
> Um das Problem zu lösen muss die Variable `RATELIMIT` (in bytes/s) in Zeile 74 getweaked werden. Ich habe ja leider keine Internetverbindung, die schnell genug ist um das Ratelimit der GTV CDN Server zu erreichen. Könntest du bitte von `13000000` (13 MByte/s) aus hochgehen und damit herausfinden ab wann das triggert?
> 
> Wenn du willst kannst du auch das Repo forken, bei dir vom Branch bugfix/ratelimiting aus einen eigenen Branch abzweigen (z.B. bugfix/ratelimiting-tweak), und im Anschluss einen PR von deinem Branch nach bugfix/ratelimiting in diesem Repo machen. So würdest du in der Liste der Contributor auftauchen (soweit ich weiß).

also habe jetzt 10 probiert. Sofort kam der Fehler. Es scheint wohl nicht an der downloadrate zu liegen. 

```
python3 gtv-dl.py 768
Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1451, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pfad/gtvdownloader/gtv-dl.py", line 312, in <module>
    v.print_title()
  File "/pfad/gtvdownloader/gtv-dl.py", line 201, in print_title
    self.get_meta()
  File "/pfad/gtvdownloader/gtv-dl.py", line 283, in get_meta
    self._gtv_get_formats()
  File "/pfad/gtvdownloader/gtv-dl.py", line 197, in _gtv_get_formats
    avail_formats_m3u8 = request_get(cdn_url_pl_avail_streams, GTVideoStream._CDN_HEADERS).decode()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pfad/gtvdownloader/gtv-dl.py", line 24, in request_get
    with _request.urlopen(req) as resp:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by ChaoticByte** [comment]
> also habe jetzt 10 probiert. Sofort kam der Fehler. Es scheint wohl nicht an der downloadrate zu liegen.

Und du konntest vor dem Aufrufen des Skripts bereits wieder auf Gronkh.tv Videos schauen? Wenn nicht, ist deine momentane IP-Adresse vermutlich noch auf den GronkhTV Servern gesperrt.
Du solltest eine neue IP-Adresse bekommen wenn du deinen Router neu startest (am besten kurz warten nach dem Ziehen des Steckers, oder direkt in der Router-Konfigurationsoberfläche auf 'neu verbinden' klicken). Kannst du z.B. mit https://api.ipify.org/ überprüfen.

Wenn das auch nicht hilft, liegt es eventuell an etwas anderem. Verwendest du ein VPN oder TOR? Greifst du von DE aus auf die Server zu? Welchen Internetprovider hast du?

**Comment by Serph91P** [comment]
> > also habe jetzt 10 probiert. Sofort kam der Fehler. Es scheint wohl nicht an der downloadrate zu liegen.
> 
> Und du konntest vor dem Aufrufen des Skripts bereits wieder auf Gronkh.tv Videos schauen? Wenn nicht, ist deine momentane IP-Adresse vermutlich noch auf den GronkhTV Servern gesperrt. Du solltest eine neue IP-Adresse bekommen wenn du deinen Router neu startest (am besten kurz warten nach dem Ziehen des Steckers, oder direkt in der Router-Konfigurationsoberfläche auf 'neu verbinden' klicken). Kannst du z.B. mit https://api.ipify.org/ überprüfen.
> 
> Wenn das auch nicht hilft, liegt es eventuell an etwas anderem. Verwendest du ein VPN oder TOR? Greifst du von DE aus auf die Server zu? Welchen Internetprovider hast du?

Das hatte ich tatsächlich nicht getestet. Das mit der IP funktioniert bei mir leider nicht wegen Vodafone Kabel Internet. Kein von oder ähnliches.

**Comment by ChaoticByte** [comment]
Vielleicht hilft das: https://forum.vodafone.de/t5/St%C3%B6rungen-im-Kabel-Netz/Neue-IP-vom-Provider-bekommen/m-p/3066664/highlight/true#M516645

**Comment by Serph91P** [comment]
> Vielleicht hilft das: https://forum.vodafone.de/t5/St%C3%B6rungen-im-Kabel-Netz/Neue-IP-vom-Provider-bekommen/m-p/3066664/highlight/true#M516645

Werde es morgen Mal mit einem von probieren. Aber danke für das kümmern.

**Comment by ChaoticByte** [comment]
> Werde es morgen Mal mit einem von probieren. Aber danke für das kümmern.

Ist das ein Typo und du meinst VPN? Weil ein VPN könnte deine Downloadrate so weit limitieren, dass du das Ratelimit der Server nicht erreichst. Auf der anderen Seite könnten VPNs eher geblockt werden, da ja viel mehr Anfragen aus einem Netz kommen. Kommt auf die Performance des VPNs. den Anbieter und die Konfiguration der Gronkh.TV Server an.

**Comment by Serph91P** [comment]
> > Werde es morgen Mal mit einem von probieren. Aber danke für das kümmern.
> 
> Ist das ein Typo und du meinst VPN? Weil ein VPN könnte deine Downloadrate so weit limitieren, dass du das Ratelimit der Server nicht erreichst. Auf der anderen Seite könnten VPNs eher geblockt werden, da ja viel mehr Anfragen aus einem Netz kommen. Kommt auf die Performance des VPNs, den Anbieter und die Konfiguration der Gronkh.TV Server an.

Ja das sollte VPN werden. Die doofe Handy Tastatur hat das korrigiert. Die Performance von meinem VPN kann meine letung ausreizen also kein Problem. Mir ging es eher um die IP Adresse und wenn ich mich nach Japan verbinden muss.

**Comment by Serph91P** [comment]
> > > Werde es morgen Mal mit einem von probieren. Aber danke für das kümmern.
> > 
> > 
> > Ist das ein Typo und du meinst VPN? Weil ein VPN könnte deine Downloadrate so weit limitieren, dass du das Ratelimit der Server nicht erreichst. Auf der anderen Seite könnten VPNs eher geblockt werden, da ja viel mehr Anfragen aus einem Netz kommen. Kommt auf die Performance des VPNs, den Anbieter und die Konfiguration der Gronkh.TV Server an.
> 
> Ja das sollte VPN werden. Die doofe Handy Tastatur hat das korrigiert. Die Performance von meinem VPN kann meine letung ausreizen also kein Problem. Mir ging es eher um die IP Adresse und wenn ich mich nach Japan verbinden muss.

es lag wohl wirklich an meiner ip. Hatte vor ungefähr einem monat eine neue bekommen. Seit dem konnte ich auch mit jdownloader ect nicht runterladen. VPN funktioniert. ich würde dann noch das limit austesten wo der server sagt das zu viel.

**Comment by Serph91P** [comment]
> > Werde es morgen Mal mit einem von probieren. Aber danke für das kümmern.
> 
> Ist das ein Typo und du meinst VPN? Weil ein VPN könnte deine Downloadrate so weit limitieren, dass du das Ratelimit der Server nicht erreichst. Auf der anderen Seite könnten VPNs eher geblockt werden, da ja viel mehr Anfragen aus einem Netz kommen. Kommt auf die Performance des VPNs, den Anbieter und die Konfiguration der Gronkh.TV Server an.

btw. noch was ist das gewollt das das den stream mit 720p und 30fps runterlädt. Es funktioniert übrigens mit der vollen leitung also 100mbs

**Comment by ChaoticByte** [comment]
> btw. noch was ist das gewollt das das den stream mit 720p und 30fps runterlädt

Per default werden Videos in 720p heruntergeladen. Du kannst aber ein anderes Format angeben. Mit `./gtv-dl.py --list-formats 690` kannst du die verfügbaren Formate für ein Video anzeigen lassen und mit `./gtv-dl.py --format 1080p60 690` das Video dann in dem entsprechenden Format herunterladen.

> Es funktioniert übrigens mit der vollen leitung also 100mbs

Okay das ist interessant. Hoffentlich trifft das nicht nur auf Netze zu die bekannterweise von VPN Providern genutzt werden.
Ich würde mich freuen wenn du es noch einmal ohne VPN versuchst sobald du eine neue IP hast. Kannst aber das Issue auch schließen wenn du das nicht möchtest.

Fyi: Ich habe mir überlegt den Downloader neu zu schreiben (in Go), mit mehr Features, besserer Erweiterbarkeit (z.B. wenn Gronkh auch seine Let's Plays auf GronkhTV hochlädt), und ganz vielleicht auch einer GUI. Das Repo hier würde ich dann archivieren wenn es soweit ist. Dann nicht wundern :D

Hab nen schönen Abend ^^

**Comment by Serph91P** [comment]
> > btw. noch was ist das gewollt das das den stream mit 720p und 30fps runterlädt
> 
> Per default werden Videos in 720p heruntergeladen. Du kannst aber ein anderes Format angeben. Mit `./gtv-dl.py --list-formats 690` kannst du die verfügbaren Formate für ein Video anzeigen lassen und mit `./gtv-dl.py --format 1080p60 690` das Video dann in dem entsprechenden Format herunterladen. Mehr dazu [hier](https://github.com/ChaoticByte/GronkhTV-Downloader#usage).
> 
> > Es funktioniert übrigens mit der vollen leitung also 100mbs
> 
> Okay das ist interessant. Hoffentlich trifft das nicht nur auf Netze zu die bekannterweise von VPN Providern genutzt werden. Ich würde mich freuen wenn du es noch einmal ohne VPN versuchst sobald du eine neue IP hast. Kannst aber das Issue auch schließen wenn du das nicht möchtest.
> 
> Fyi: Ich habe mir überlegt den Downloader neu zu schreiben (in Go), mit mehr Features, besserer Erweiterbarkeit (z.B. wenn Gronkh auch seine Let's Plays auf GronkhTV hochlädt), und ganz vielleicht auch einer GUI. Das Repo hier würde ich dann archivieren wenn es soweit ist. Dann nicht wundern :D
> 
> Hab nen schönen Abend ^^
> 
> EDIT: Habe in einem weiteren Commit im bugfix/ratelimiting Branch hinzugefügt, dass die aktuelle Download-Rate mit ausgegeben wird. Vlt. hilft das noch weiter.

Ah danke dafür für die weiteren Befehle.

 Ja ich dachte an einen docker wo dann alles drin ist mit webgui (wäre perfekt für Leute zum benutzen wegen dependencies usw.) Python hatte ich besser helfen können. Gonhabe ich gar keine Ahnung :D

**Comment by ChaoticByte** [comment]
> Ja ich dachte an einen docker wo dann alles drin ist mit webgui (wäre perfekt für Leute zum benutzen wegen dependencies usw.) Python hatte ich besser helfen können. Gonhabe ich gar keine Ahnung :D

Go kompiliert direkt statisch gelinkte Executables, d.h. im Idealfall gibt es überhaupt keine Abhängigkeiten für die Enduser ^^

**Comment by Serph91P** [comment]
download bei meiner ip schlägt sofort fehlt. Der Ban scheint länger wie 24h

**Comment by ChaoticByte** [comment]
> download bei meiner ip schlägt sofort fehlt. Der Ban scheint länger wie 24h

Ja, vermutlich um einiges länger. Ich hoffe dass du schnell eine neue IP Adresse bekommst :/

**Comment by Serph91P** [comment]
> > download bei meiner ip schlägt sofort fehlt. Der Ban scheint länger wie 24h
> 
> Ja, vermutlich um einiges länger. Ich hoffe dass du schnell eine neue IP Adresse bekommst :/

Normalerweise wenn nicht kaputt geht have ich für mehrere Monate wenn nicht Jahre die gleiche IP.

**Comment by ChaoticByte** [comment]
Hast du eine statische IP-Adresse?

**Comment by Serph91P** [comment]
> Hast du eine statische IP-Adresse?

So fast ja. War bei mir schon immer so seit dem im Kabel Internet haben, das dir sich nur sehr schwer ändern lässt bzw. Ändert.

**Comment by ChaoticByte** [comment]
Das ist ja blöd :(
Ist natürlich ganz gut um Dinge zu hosten (wenn das bei Kabel geht, ich hab mal gehört das soll nicht bei allen Anbietern funktionieren).

**Comment by Serph91P** [comment]
> Das ist ja blöd :( Ist natürlich ganz gut um Dinge zu hosten (wenn das bei Kabel geht, ich hab mal gehört das soll nicht bei allen Anbietern funktionieren).

gibt heutzutage genug mittel um das zu umgehen, weiß aber auch nicht welche anbeiter das blockieren.

**Comment by ChaoticByte** [comment]
Ich meinte eher dass es aus technischen Gründen nicht mit allen Anbietern funktioniert (funktioniert hat?). Aber ja, man kann in der IT alles irgendwie umgehen.

Meld dich gerne wenn du was neues zu dem Thema hast (oder du nen anderen Fehler findest oder ne Anregung hast). Ich würd dann jetzt erstmal das bug-Label von dem Issue entfernen, ebenso von dem PR. Der Port nach Go ist bereits in Arbeit, wenn du willst kannst du mir ja auf Github folgen, dann bekommst du's mit wenn ich die erste Version release. Ich werd aber auch das Issue hier closen sobald der Port veröffentlicht ist, und das Repo hier archivieren, also mitbekommen wirst du's so oder so ^^

Schönen Sonntag

**Comment by ChaoticByte** [comment]
@Serph91P ich habe gerade (beim porten nach Go) selber erlebt dass die Server mich stark ausgebremst haben, teilweise war gar keine Verbindung mehr zu den Servern möglich. Mit neuer IP geht es wieder.
Ich werde ein Ratelimiting auch in die Go-Version einbauen. Werde nur nicht so schnell ausgesperrt wie du, weil meine Internetleitung doch etwas langsamer ist als deine ^^

**Comment by ChaoticByte** [comment]
@Serph91P 
Der neue Downloader [lurch-dl](https://github.com/ChaoticByte/lurch-dl) ist ready :D
Ich schließe das Issue.
